import { mkdirSync, writeFileSync } from "node:fs";
import { deflateSync } from "node:zlib";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const here = dirname(fileURLToPath(import.meta.url));
const root = resolve(here, "..");
const buildDir = resolve(root, "build");

const crcTable = new Uint32Array(256);
for (let i = 0; i < 256; i++) {
  let c = i;
  for (let j = 0; j < 8; j++) c = c & 1 ? 0xedb88320 ^ (c >>> 1) : c >>> 1;
  crcTable[i] = c >>> 0;
}
function crc32(buf) {
  let c = 0xffffffff;
  for (let i = 0; i < buf.length; i++)
    c = (crcTable[(c ^ buf[i]) & 0xff] ^ (c >>> 8)) >>> 0;
  return (c ^ 0xffffffff) >>> 0;
}
function pngChunk(type, data) {
  const len = Buffer.alloc(4);
  len.writeUInt32BE(data.length, 0);
  const typeBuf = Buffer.from(type, "ascii");
  const crc = Buffer.alloc(4);
  crc.writeUInt32BE(crc32(Buffer.concat([typeBuf, data])), 0);
  return Buffer.concat([len, typeBuf, data, crc]);
}

function makePng(width, height, getPixel) {
  const sig = Buffer.from([0x89, 0x50, 0x4e, 0x47, 0x0d, 0x0a, 0x1a, 0x0a]);
  const ihdr = Buffer.alloc(13);
  ihdr.writeUInt32BE(width, 0);
  ihdr.writeUInt32BE(height, 4);
  ihdr[8] = 8;
  ihdr[9] = 6;
  ihdr[10] = 0;
  ihdr[11] = 0;
  ihdr[12] = 0;
  const raw = Buffer.alloc(height * (1 + width * 4));
  let p = 0;
  for (let y = 0; y < height; y++) {
    raw[p++] = 0;
    for (let x = 0; x < width; x++) {
      const px = getPixel(x, y);
      raw[p++] = px.r;
      raw[p++] = px.g;
      raw[p++] = px.b;
      raw[p++] = px.a;
    }
  }
  const idat = deflateSync(raw);
  return Buffer.concat([
    sig,
    pngChunk("IHDR", ihdr),
    pngChunk("IDAT", idat),
    pngChunk("IEND", Buffer.alloc(0)),
  ]);
}

function drawIcon(size) {
  const margin = size * 0.18;
  const stemWidth = Math.max(2, Math.round(size * 0.16));
  const barHeight = Math.max(2, Math.round(size * 0.18));
  const cx = size / 2;
  const top = margin;
  const right = size - margin;
  const left = margin;
  const stemLeft = cx - stemWidth / 2;
  const stemRight = cx + stemWidth / 2;
  const bottom = size - margin;
  return (x, y) => {
    const t = y / size;
    const bgR = Math.round(28 + t * 30);
    const bgG = Math.round(38 + t * 36);
    const bgB = Math.round(56 + t * 48);
    const inBar = y >= top && y <= top + barHeight && x >= left && x <= right;
    const inStem = x >= stemLeft && x <= stemRight && y >= top && y <= bottom;
    if (inBar || inStem) return { r: 240, g: 240, b: 240, a: 255 };
    return { r: bgR, g: bgG, b: bgB, a: 255 };
  };
}

function makeIco(pngBuffer, width, height) {
  const w = width >= 256 ? 0 : width;
  const h = height >= 256 ? 0 : height;
  const header = Buffer.alloc(6);
  header.writeUInt16LE(0, 0);
  header.writeUInt16LE(1, 2);
  header.writeUInt16LE(1, 4);
  const entry = Buffer.alloc(16);
  entry[0] = w;
  entry[1] = h;
  entry[2] = 0;
  entry[3] = 0;
  entry.writeUInt16LE(1, 4);
  entry.writeUInt16LE(32, 6);
  entry.writeUInt32LE(pngBuffer.length, 8);
  entry.writeUInt32LE(6 + 16, 12);
  return Buffer.concat([header, entry, pngBuffer]);
}

mkdirSync(buildDir, { recursive: true });

const tray16 = makePng(16, 16, drawIcon(16));
const tray32 = makePng(32, 32, drawIcon(32));
const app256 = makePng(256, 256, drawIcon(256));
const ico = makeIco(app256, 256, 256);

writeFileSync(resolve(buildDir, "tray.png"), tray16);
writeFileSync(resolve(buildDir, "tray@2x.png"), tray32);
writeFileSync(resolve(buildDir, "icon.png"), app256);
writeFileSync(resolve(buildDir, "icon.ico"), ico);

const tsOut = `// Generated by scripts/generate-icons.mjs. Do not edit by hand.
export const TRAY_ICON_PNG_BASE64 = '${tray16.toString("base64")}';
export const TRAY_ICON_PNG_2X_BASE64 = '${tray32.toString("base64")}';
`;
writeFileSync(resolve(root, "src/main/tray-icon-data.ts"), tsOut);

process.stdout.write(
  `Wrote icons to ${buildDir}/ and src/main/tray-icon-data.ts\n`,
);
